name: paginated_query_stream_builder
description: The library for building list and grid views from paginated Firestore query streams.
version: 0.1.0
homepage: https://github.com/kostyan0005/paginated_query_stream_builder

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: any
  logger: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
